### ISSUE TITLE
My user profile returns a `500` page

### ISSUE THREAD

**Issue by ehmicky** [pgrimaud/git-stars#37]
Thanks for this project, it's awesome!

My user profile (https://git-stars.com/user/ehmicky) is showing this (with a `500` status code):

![Screenshot from 2022-08-17 18-17-57](https://user-images.githubusercontent.com/8136211/185191170-44e8768e-5947-405b-8130-0554ceaf2fff.png)

It worked until I click on "Refresh" on my own profile.
Refreshing the page does not seem to fix the problem.

**Comment by pgrimaud** [comment]
I just fixed it, sorry about it 😄

**Comment by ehmicky** [comment]
Thanks a lot for the quick fix and answer! :heart:
