### ISSUE TITLE
My user profile returns an error page

### ISSUE THREAD

**Issue by AmraniCh** [pgrimaud/git-stars#41]
Hey, thanks for this awesome project.

When I do login or want to refresh my user I get this error, can you please fix this ?

![image](https://user-images.githubusercontent.com/49124992/209455084-22da27e1-06dd-4475-b188-5bbce7e6955d.png)

**Comment by pgrimaud** [comment]
I just fixed the issue... Weird issue with the last upgrade of AMQP 😢

**Comment by AmraniCh** [comment]
Thanks!!

**Comment by AmraniCh** [comment]
@pgrimaud can you fix the same problem with this [organization ](https://github.com/lazzard) please ?
